time ./convert.sh ./TestFile/doc:docx/doc-small.docx ./outputs/doc/ image
time ./convert.sh ./TestFile/doc:docx/doc-medium.docx ./outputs/doc/ image
time ./convert.sh ./TestFile/doc:docx/doc-large.docx ./outputs/doc/ image
time ./convert.sh ./TestFile/hwp/hwp-small.hwp ./outputs/hwp/ image
time ./convert.sh ./TestFile/hwp/hwp-medium.hwp ./outputs/hwp/ image
time ./convert.sh ./TestFile/hwp/hwp-large.hwp ./outputs/hwp/ image
time ./convert.sh ./TestFile/ppt:pptx/ppt-small.pptx ./outputs/ppt/ image
time ./convert.sh ./TestFile/ppt:pptx/ppt-medium.pptx ./outputs/ppt/ image
time ./convert.sh ./TestFile/ppt:pptx/ppt-large.pptx ./outputs/ppt/ image
time ./convert.sh ./TestFile/xls:xlsx/xlsx-small.xlsx ./outputs/xlsx/ image
time ./convert.sh ./TestFile/xls:xlsx/xlsx-medium.xlsx ./outputs/xlsx/ image
time ./convert.sh ./TestFile/xls:xlsx/xlsx-large.xlsx ./outputs/xlsx/ image